package com.wwc.sg.dw.representations;

import javax.persistence.*;

@Entity
@Table(name = "book")
@NamedQueries({
        @NamedQuery(name = "Book.findAll",
                query = "select b from Book b"),
        @NamedQuery(name = "Book.findByTitle",
                query = "select b from Book b where upper(b.title) like upper(:title)")
})
public class Book {

    /**
     * Entity's unique identifier.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "title")
    private String title;

    @Column(name = "author")
    private String author;

    public Book() {
    }

    /**
     * A constructor to create book.
     * Id is not passed, cause it's auto-generated by RDBMS.
     *
     * @param title
     * @param author
     *
     **/
   public Book(String title, String author) {
        this.title = title;
        this.author = author;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }
}
